### ISSUE TITLE
Email notifications not received when new CVE created

### ISSUE THREAD

**Issue by malwarenator** [opencve/opencve#123]
I have been using the online instance of OpenCVE (https://www.opencve.io) with a number of CPEs added.

## Expected Behavior

With the notification "When a new CVE is created" enabled in "Report filters", email notification is received when a new CVE is created.

## Actual Behavior

With the above notification enabled, I do not get email notifications for a new CVE. If I enable other settings like when CVSS score changes, I do get email notifications.

## Specifications

  - Platform: Online instance

## Screenshots (optional)

Notification settings:
![OpenCVE](https://user-images.githubusercontent.com/86147805/126028486-b26871b7-d7f8-48ee-b630-c845c10c47ca.png)

**Comment by ncrocfer** [comment]
What is the vendors or products you subscribed ? If new CVE concerning them are first created without associated CPE (and the NVD often do that), the alert will trigger the "When a CVE is updated" notification, not in the "When a new CVE is created".

Give us the list we'll be able to check.

**Comment by malwarenator** [comment]
This is the list:

- Windows 7, 8.1, 10, Server 2008, Server 2012, Server 2016
- SharePoint Enterprise Server 2016
- Wordpress

**Comment by ncrocfer** [comment]
Thanks. So I confirm what I said:

- sometimes when the CVE are created no CPE is associated,
- then later a change appears (summary changed, CVSS score changed, etc) -> it's not anymore `new_cve` event

For example the last updated CVE for Wordpress is [CVE-2021-29447](https://www.opencve.io/cve/CVE-2021-29447), published on 2021-04-15 with the following payload:

```json
{
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "cve": {
        "CVE_data_meta": {
            "ASSIGNER": "cve@mitre.org",
            "ID": "CVE-2021-29447"
        },
        "data_format": "MITRE",
        "data_type": "CVE",
        "data_version": "4.0",
        "description": {
            "description_data": [{
                    "lang": "en",
                    "value": "Wordpress is an open source CMS. A user with the ability to upload files (like a
                    n Author) can exploit an XML parsing issue in the Media Library leading to XXE attacks.This require
                s WordPress installation to be using PHP 8. Access to internal files is possible in a successful XXE
                attack.This has been patched in WordPress version 5.7 .1, along with the older affected versions vi
                a a minor release.We strongly recommend you keep auto - updates enabled.
                "
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [{
            "description": [{
                "lang": "en",
                "value": "CWE-611"
            }]
        }]
    },
    "references": {
        "reference_data": [{
                "name": "https://github.com/WordPress/wordpress-develop/security/advisories/GHSA-rv47-pc52 -
                    qrhh ",
                "refsource": "CONFIRM",
                "tags": [],
                "url": "https://github.com/WordPress/wordpress-develop/security/advisories/GHSA-rv47-pc52-
                qrhh "
            },
            {
                "name": "https://wordpress.org/news/category/security/",
                "refsource": "MISC",
                "tags": [],
                "url": "https://wordpress.org/news/category/security/"
            }
        ]
    }
},
"impact": {},
"lastModifiedDate": "2021-04-15T21:18Z",
"publishedDate": "2021-04-15T21:15Z"
}
```

As you can see no configuration (so no vendor or product) is associated, that's why you can't receive notification concerning a new CVE.

**Comment by malwarenator** [comment]
Thanks for the detailed answer.

**Comment by pasdesignal** [comment]
I understand why this behaviour happens but I wonder if it’s acceptable going forward.

I think using the notification setting “When a new CVE is created" is something many users will do to avoid the ‘noise’ of updated historical CVEs. I certainly have adopted this stance. But if it doesn’t work in some cases they may miss important new CVEs. 

Is there a way to mitigate this limitation maybe by :
1. using a string match in the CVE description data as well as the CPE data?
OR
2. Do not consider a CVE a “new_cve” event until it has CPE data?
3. At least warn users who turn off notifications for CVE updates that they may miss new CVEs due to this limitation?

Great project, following closely. Keep up the good work.
