### ISSUE TITLE
SSL for opencve site

### ISSUE THREAD

**Issue by 0xMLNK** [opencve/opencve#127]
Hi every one, 

First, thank you for great product. 
I have deployed opencve as docker to my server and everything works fine. 
But I can't find the way, how to include ssl for the webpage. 
Do you have some best practice? 
TY

**Comment by facyber** [comment]
Hi @0xMLNK 

You can use reverse proxy (Apache for example) and then use Lets Encrypt. I managed to do that, but only using SSL for very same server name. For example if you name your server ocvesrv01 and your domain is example.com, I managed to make it work only for ocvesrv01.example.com, not something better like cve.example.com.

So the summary:
Web Server: Apache
TLS: Lets Encrypt
ServerName: FQDN

And important part, in opencve.cfg, set "server_name =" empty. Can't remember why it does not work without, something about linking to localhost instead of fqdn, or something, there is some issue in this repository regard that.

Hope this helps.

**Comment by 0xMLNK** [comment]
Thank you for a fast and helpful answer!
