### ISSUE TITLE
No Alert/Notification for new Zero Day log4j CVE which Vendor/Product we already subscribed to!

### ISSUE THREAD

**Issue by frostnite** [opencve/opencve#157]
![image](https://user-images.githubusercontent.com/14076246/145788113-25c5cb97-5d00-4a7d-994b-f95481690709.png)

On OpenCVE notification setting, we have an option that alerts/notifies when there is a new CVE for our subscribed Vendor/Product. However, it is basically useless since every new CVE published on NVD NIST has no CPE. 

We usually have to depend on the "CVE is updated alert option" when "its CPE List changes" and this usually take up to a week before NVD NIST add/update the CPE list for that new CVE. This resulted in a few days (up to a week)delay before we get notified of a new vulnerability for our subscribed Vendor/Product.

Let's take a look at the recent Zero-Day Log4j CVE-2021-44228 which was published on 10th Dec 2021. Even though we are subscribed to the Product "Log4j" on OpenCVE, till now as of 13th Dec 2021, we still do not get any notification of that vulnerability/"New CVE Created".

Is anyone facing this delayed notification issue? 
Is the "new CVE" notification/alert for our subscribed Vendor/Product solely based on the CPE List on NVD NIST? If that is the case, then there will always be a few days delay(Up to a week) before we get notified of a new CVE.

**Comment by M0dEx** [comment]
Yes, the vendor/product alerts are solely based on data from NVD NIST, which still unfortunately does not have a CPE list for CVE-2021-44228 and neither does Mitre.

**Comment by frostnite** [comment]
> Yes, the vendor/product alerts are solely based on data from NVD NIST, which still unfortunately does not have a CPE list for [CVE-2021-44228](https://github.com/advisories/GHSA-jfh8-c2jp-5v3q) and neither does Mitre.

I think it would be great to add a subscription feature based on "Keyword Search in Description". So if the keyword "log4j" exist in a newly published CVE description, add the entry in OpenCVE dashboard as well as send an Email Alert.

**Comment by M0dEx** [comment]
> I think it would be great to add a subscription feature based on "Keyword Search in Description". So if the keyword "log4j" exist in a newly published CVE description, add that CVE entry in OpenCVE dashboard as well as send an Email Alert. 
So something like #105?

**Comment by frostnite** [comment]
> > I think it would be great to add a subscription feature based on "Keyword Search in Description". So if the keyword "log4j" exist in a newly published CVE description, add that CVE entry in OpenCVE dashboard as well as send an Email Alert.
> 
> So something like #105?

Yes, having a subscription based on "search term in the description" will help speed up the process of getting notified of a new vulnerability rather than waiting for NVD NIST to add the CPE list which takes forever (based on my observation, they can take up to 2 weeks max which caused SLA gap in our monitoring).

**Comment by M0dEx** [comment]
@ncrocfer I think this would be a good addition to OpenCVE. I have already partly drafted a possible implementation. When I'm done, I can create a PR.

What do you say?

**Comment by ncrocfer** [comment]
Hi @M0dEx ,

What @frostnite is asking is something I already think about, and definitively I have to work on that. I have a started branch for that, I will check if I have time to finish it before end of the month (it will be a new type of events to be alerted when a subscribed vendor/product appears in a change).

The other feature request (subscribe to search) is another needs, and yes if you want to start on it you can of course ;)

**Comment by frostnite** [comment]
> Hi @M0dEx ,
> 
> What @frostnite is asking is something I already think about, and definitively I have to work on that. I have a started branch for that, I will check if I have time to finish it before end of the month (it will be a new type of events to be alerted when a subscribed vendor/product appears in a change).
> 
> The other feature request (subscribe to search) is another needs, and yes if you want to start on it you can of course ;)

(it will be a new type of events to be alerted when a subscribed vendor/product appears in a change) - What do you mean by subscribed vendor/product appears in a change? Isn't that already part of "CPE List Changes" Option?

You might want to consider this instead ~ a new alert should trigger when our subscribed Vendor/Product Name appears in NVD NIST's CVE Description. This will be better than relying on and waiting for NVD NIST to add/update the CPE list.

**Comment by M0dEx** [comment]
> (it will be a new type of events to be alerted when a subscribed vendor/product appears in a change) - What do you mean by subscribed vendor/product appears in a change? Isn't that already part of "CPE List Changes" Option already?
> 
> You might want to consider this instead ~ a new alert should trigger when our subscribed Vendor/Product Name appears in a ****newly published** CVE** Description. This will be better than relying on and waiting for NVD NIST to add/update the CPE list.

I think that is what @ncrocfer meant.

**Comment by ncrocfer** [comment]
> You might want to consider this instead ~ a new alert should trigger when our subscribed Vendor/Product Name appears in a newly published CVE Description. This will be better than relying on and waiting for NVD NIST to add/update the CPE list.

Ouch... Did you consider the number of false positives you will receive? Trust me, if CPE have been created it's for a good reason, no need to search vendor/product in description. But apart that I'm still ok to add this feature, sometimes you have to search specific keywords so why not :)

>  Isn't that already part of "CPE List Changes" Option already?

It's not really the same things, the `cpe`event is raised when any vendors or products are added, even those you're not interested by. What I'm talking is a special event saying "Ok you're interesting by `apache` vendor, please note this vendor first appeared in this existing CVE". After that no new alert will be raised because the first apparition is already done.

**Comment by frostnite** [comment]
> > You might want to consider this instead ~ a new alert should trigger when our subscribed Vendor/Product Name appears in a newly published CVE Description. This will be better than relying on and waiting for NVD NIST to add/update the CPE list.
> 
> Ouch... Did you consider the number of false positives you will receive? Trust me, if CPE have been created it's for a good reason, no need to search vendor/product in description. But apart that I'm still ok to add this feature, sometimes you have to search specific keywords so why not :)
> 
> > Isn't that already part of "CPE List Changes" Option already?
> 
> It's not really the same things, the `cpe`event is raised when any vendors or products are added, even those you're not interested by. What I'm talking is a special event saying "Ok you're interesting by `apache` vendor, please note this vendor first appeared in this existing CVE". After that no new alert will be raised because the first apparition is already done.

**Comment by frostnite** [comment]
> > > You might want to consider this instead ~ a new alert should trigger when our subscribed Vendor/Product Name appears in a newly published CVE Description. This will be better than relying on and waiting for NVD NIST to add/update the CPE list.
> > 
> > 
> > Ouch... Did you consider the number of false positives you will receive? Trust me, if CPE have been created it's for a good reason, no need to search vendor/product in description. But apart that I'm still ok to add this feature, sometimes you have to search specific keywords so why not :)

I understand that it will have more false positives but it can be an optional configuration that can be enabled by the user since just relying on the CPE list to get added/updated for new CVE may take few days to week.

**Comment by ncrocfer** [comment]
The PR #162 will close this issue. For clarity, and not to mix up requests, I keep #105 opened for the "search in description" feature.

**Comment by jbmaillet** [comment]
@M0dEx #pedantic_mode_on _"...which still unfortunately does not have a CPE list for CVE-2021-44228 and neither does Mitre."_
MITRE never had and never will have any CVSS nor CPE: this is simply not part of their job: MITRE is just the default CNA, that happens to also be in charge of CWE specification and catalog, so you'll get this too. CPE and CVSS are only the job of NVD analysts are in charge of this. On MITRE only CVE Id, description, references and CWE. Basicaly, go to MITRE only on the last resort.
#pedantic_mode_off

I would second that demand, and would not care about having false positives.

**My use case:** I work in the embedded / IoT field, more precisely automotive. The actors in this industry are like new borns that discover the cybersec domain yesterday (in spite of decades of experience in the _safety_ field, but that's just a _related_ field to cybersec, that started with safety belts in the 50s). With the noticeably exception of Tesla, these people are looking to CVE as "a chicken would found a knife" (French saying for "staying in awe and not having the slightest idea of what to do with it"). I monitor a list of about a hundred industrial actors in the field for CVE on their products, and every super-rare finding is a jewel to me. I have a full replication of the NVD, and a full list of CPE strings extracted from it that I maintain in a text file under git, updated weekly,  checking for the new ones.

This would be my personal example for a use case of such feature, and this is about finding the needle in the haystack, not gaining a couple of days on an early notification. So I would not be afraid to be overwhelmed by false positives (at least for the foreseeable future), because I would use it as a feature for a niche usage, out of the mainstream CVE flow.
