### ISSUE TITLE
Missing CVSS, Products, and CWE details for CVE-2022-0778

### ISSUE THREAD

**Issue by illandril** [opencve/opencve#188]
## Expected Behavior
CVE-2022-0778 should include...
 - CVSS: 7.5 (CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H)
 - Products: OpenSSL
 - CWE: 835

## Actual Behavior
CVE-2022-0778 has...
 - CVSS: No CVSS
 - Products: No product
 - CWE: No CWE

## Steps to Reproduce the Problem
1. Open https://www.opencve.io/cve/CVE-2022-0778
2. Compare the details with what is available from Mitre and NVD

## Specifications

  - OpenCVE version: opencve.io accessed on March 21

**Comment by ncrocfer** [comment]
This is not a bug of OpenCVE, it's because the NVD hasn't updated his JSON feed yet. You can check it here: https://nvd.nist.gov/vuln/data-feeds#JSON_FEED

If you open the `CVE-Recent` file used by OpenCVE to synchronize its database you will see that the **CVE-2022-0778** is not updated yet (see the **configurations**, **impact** and **problemtype** keys):

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/1552526/159334263-51b9cb01-b3cd-4a0d-a04d-cb9887cc1d90.png">

So the NVD updated the page of the CVE but not the JSON feed.
