### ISSUE TITLE
How long do take emails to be processed on https://www.opencve.io ?

### ISSUE THREAD

**Issue by pierreozoux** [opencve/opencve#190]
It is more a question than a bug report, sorry for the noise already.
(But I don't know where to ask such question, your twitter account was banned apparently :upside_down_face: )

First of, thanks a lot for your service, I'm really happy \o/ and I'd be willing to pay to help maintain it, it is really good, and was exactly what I was looking for!

I just have a question about this CVE:
https://www.opencve.io/cve/CVE-2022-0735

It was published the 28th of March here:
https://gitlab.com/gitlab-org/cves/-/blob/master/2022/CVE-2022-0735.json

Apparently, it was registered in the platform at this date as well:
![Screenshot from 2022-04-05 10-51-29](https://user-images.githubusercontent.com/1863453/161716908-6529497b-3f8a-4de0-bdb3-f006d3f3adcd.png)

But we received the email, only yesterday, the 4th April. I'd have liked to be warn on the day, and I'd love that the situation is improved :)

My question is just why it takes 1 week between the CVE and the email?
(I'm not asking that you process it faster or whatever, currently, I don't pay, so I'm in a bad position to demand anything :) I just want to understand why is that, and maybe if I can help to resolve, or if it would always be like that? )

Thanks a lot again for this platform, and for your time to develop and maintain it!

cheers!

**Comment by jbmaillet** [comment]
Hi. I am not a maintainer of OpenCVE and know nothing from its internal architecture - I'm just an "experimental user of it". But I know a bit about the CVE ecosystem ;-)

If you subscribed for notification on gitlab products (or any CPE from any vendor for any CVE), would be that after transfer from the top-level-CNA MITRE to the NVD on 29229328, NVD's analysts only reviewed this CVE one week latter on 20220404,  and then and only then updated it with its impacted CPE records:
[https://nvd.nist.gov/vuln/detail/CVE-2022-0735#VulnChangeHistorySection](https://nvd.nist.gov/vuln/detail/CVE-2022-0735#VulnChangeHistorySection)
(click on the "show changes")

As long as you don't have any CPE attached to a CVE, the only way to find it beforehand would be to do a full text search in the CVE descriptions on your NVD replication database (or on MITRE in the future, when they'll get decent data feeds, though CPE are and will stay out of the scope of MITRE).

**Comment by pierreozoux** [comment]
hey @jbmaillet 

Thanks a lot, it does explain everything I guess :) Nist takes a week to "rate" them.. Hum... :thinking: I wonder why ;) (My conspiration brain could see a reason ;) But I also understand they need time to process this :) )

Then I guess my question for opencve becomes, can we configure to get the raw first report and/or the report rated by nist?

Thanks again for the amazing work \o/

**Comment by jbmaillet** [comment]
@pierreozoux in all this CVE workflow, remember there are human beings acting behind the scene, and the analysts, both at MITRE which is the last-resort CNA (and at other CNA as well) and at the NIST/NVD, that have some paperwork and analysis before providing the data that allow automation for the tooling you and I are leveraging. They do it in a smart way, and this imply prioritization per budget, per rough estimated severity, and per the workload at the time.

Details bellow, if TL;DR you can jump right to conclusions.

**Per budget:** I think NIST/NVD, being US federal public administrations, and working in coordination with others such as the (relatively new CISA), have decent and stable budget. But as for MITRE, this is a "not-for-profit private company" subcontracting some paperwork for some US federal administrations - such as, but not limited to, the NVD. And I don't know how it is going right now, but when I started digging into CVE, this was a disaster. This 2016 [budget vs published CVE chart](https://www.bleepstatic.com/images/news/u/986406/attacks/Vulnerabilities/CVE-funding.png), from a Senate or House of Representatives representative is clear enough: what can you do this that? Plus in 2017, the first 100% security companies became CNA (the first one being F-Secure IIRC), with the ability to push CVE Ids for products not directly under their responsibility, resulting in a huge surge of the number of CVE. Hope it's taken more seriously now.

**Per rough estimated severity:** it took close to 3 weeks for the [CVE-2022-26269](https://nvd.nist.gov/vuln/detail/CVE-2022-26269) discovered by a colleague of mine to get a CVE Id from MITRE. He got an acknowledge from MITRE right away after filling the web form, but still, close to 3 weeks to get a CVE Id and be able to move on. But this is just a "tampering" type of CVE. By contrast, it took me about half-a day to get 2 CVE Ids for some RCE, without user interaction, nor physical access (mere proximity, Wi-Fi issues).

**Per the workload at the time:** here are some excerpts from my CISA weekly monitoring.
2022 W06 575 CVE, 236 vendors/products impacted
2022 W07 814 CVE, 342 vendors/products impacted <--- record high number of I ever saw in 6 years of practice!
2022 W08 677 CVE, 289 vendors/products impacted
2022 W09 576 CVE, 248 vendors/products impacted
2022 W10 375 CVE, 244 vendors/products impacted
2022 W11 359 CVE, 359 vendors/products impacted
2022 W12 632 CVE, 317 vendors/products impacted <--- ouch!
2022 W13 454 CVE, 293 vendors/products impacted
2022 W14 565 CVE, 394 vendors/products impacted

**CONCLUSIONS:**

> Nist takes a week to "rate" them.. Hum... thinking I wonder why

Don't fantasize, in the vast majority of the cases they just do their best as explained above, and establish priorities.

Now, in all this, there are some balance of power / politic tricks, especially when it comes to CNA. **Long story short: an organization can decide to become a CNA just to actually block the publication of CVE on their products** (you cannot turn to MITRE because there is a CNA in charge, but the CNA in charge is dragging its feet). Recently, MITRE discovered that about 15% of the now close to 200 CNA actually _never published a single CVE in the past year_.  Another typical case: **there are also some CNA practicing "coordinated disclosure" that last forever, and/or never providing a useful, actionable CPE** (ex: Google Android is made of hundreds of repositories, but put everything in a single "android whatever kitchen sink" CPE, good luck with that if you're not a Google partner: here is a way to get some juicy "partners" contracts).

> can we configure to get the raw first report and/or the report rated by nist?

AFAIK, and as of today, not really - considering my professional ethics (and personal taste) which forbid me to use ugly web scraping ;-) Yet, there is hope, and right now strategies available from the shelves:

- MITRE as a CVE feed... as a twitter bot. You could use that and do NPL or goold old regexp on keywords.
- MITRE is undergoing a major transformation with a new web site, some services, a new CVE JSON formats.... explore [the CVE automation etc working group](https://github.com/CVEProject). What I'd like for instance would be a MITRE CVE feed [similar to the NVD one](https://nvd.nist.gov/vuln/data-feeds). BTW, the CVE JSON scheme version 5 is in release candidate state I-stopped-counting, but hey, you have 170000 CVE and more then 300000 products to migrate to that.
- If you want to get ahead of CVE publication on the NVD/OpenCVE, the [CISA weekly bulletins](https://www.cisa.gov/uscert/ncas/bulletins) are a cheap way since they are not blocked by the MITRE to NVD step.
- If you want to prioritize wisely, use the [CISA catalog of known exploited vulnerabilities](https://www.cisa.gov/known-exploited-vulnerabilities-catalog) (super easy, less than 100 lines of Python to support). Usefulness depends on the products you use.
- Similarly, and works for issues that are still "RESERVED" or blocked on MITRE by lack of reference and did not popped-up on the NVD, use [InTheWild.io](https://inthewild.io/), also [here](https://github.com/gmatuz/inthewilddb), again super cheap to use.
- Depending on your ecosystem (completely useless to me so far, I'm into IoT/embedded), use [GHSA and its database](https://github.com/advisories). Github is a CNA, and provide a frameworks for stakeholders to handle issues, and support projects for their CVE paperwork.
- Again, depending on your ecosystem (and very useful to me), use OSV, see [here](https://osv.dev/), [here](https://osv.dev/docs/#section/What-is-OSV) and [here](https://github.com/google/oss-fuzz/tree/master/projects). And [here for the proposal paper](https://security.googleblog.com/2021/02/launching-osv-better-vulnerability.html), but it turned out a bit differently in the end.
- Last, monitor other tools beside OpenCVE. Forget about [some](https://github.com/cve-search/cve-search), but there are other excellent ones (like [here](https://github.com/vulsio/go-cve-dictionary), just a small part of [this](https://vuls.io/)).

Maybe @ncrocfer , working at OVH and closer to your use cases than I am in my IoT field, would have more actionable advices for your? In my experience, this is vastly a question of ecosystem, and there is no "one size fits all".

**Comment by ncrocfer** [comment]
Hi,

@jbmaillet First of all thanks a lot for your very clear answer ! I have carefully read all your points and I found a lot of very interesting information that I didn't know ! For instance the trick of some vendors to become CNA just to block CVE disclosure was a discovery for me :open_mouth:

I confirm what you said to @pierreozoux (in fact your answer was so complete that I have almost nothing to add ^^). OpenCVE is only based on NVD for now, so you have to use other tools to be fully updated.

To be transparent I'm aware of this problem of *freshness* data in OpenCVE. Some users already noticed me when a CVE has been published somewhere but not yet on OpenCVE, for instance when the CVE is still **RESERVED** on the MITRE (so not taken into account by NVD).

This is the reason I'm currently working to understand where the cybersecurity community finds the latest security news. For instance I think it can be interesting to fetch the [RHSA feed](https://access.redhat.com/documentation/en-us/red_hat_security_data_api/1.0/html/red_hat_security_data_api/cvrf#list_all_cvrfs), as well as the [CVE database](https://access.redhat.com/documentation/en-us/red_hat_security_data_api/1.0/html/red_hat_security_data_api/cve#list_all_cves) of RedHat. If I'm not wrong I already seen some CVE published in this feed before the MITRE itself !

The blocker I have now is how to find the **modified date** of each item (to find the latest updated RHSA and CVE). The [NVD](https://nvd.nist.gov/vuln/data-feeds#JSON_FEED) did an awesome work to facilitate us the process:

1. First step is to fetch a sha256 hash,
2. If this hash has changed from the last time, it means some CVE have changed,
3. In this case a JSON file contains the last changes.

I'm afraid the process is more complicated on the RedHat feed (so lot's of requests to do, with the risk of being blacklisted).

Concerning the MITRE it seems they will provide us the JSON scheme v5  in late spring, it's coming soon. But I read in their [documentation](https://github.com/CVEProject/cve-schema/blob/master/schema/v5.0/docs/versions.md) they will now provide affected products. I'm lost: I thought the CPE list was managed by the NVD. Does-it mean the MITRE *recovers* the CPE management?

As you can see there are still grey areas in my mind. I think you know better than me this ecosystem, so @jbmaillet if you agree I will contact you (maybe on LinkedIn?) to discuss about it. If you have any ideas to help me on this **datasources** feature I will be very happy :smiley:

**Comment by pierreozoux** [comment]
Thanks both of you for the amazing detailed answer! I learned a lot!
I think that for my use case the current service from opencve is more than enough, and thanks again for this service!

@ncrocfer I let you close or keep open the issue, on my side, I have the answer I was looking for :)

Have a nice day!

**Comment by jbmaillet** [comment]
@pierreozoux , @ncrocfer to sum it up, it is not about the CVE, it is all about the CPE (or other product Id, such as used in the various ecosystems from OSV, including pURL).

CVE are just a constant stream from MITRE, as the last resort CNA / CVE numbering authority, in charge of 1/ ensuring that all CVE Id are unique, coming from all other CNA and 2/ making these CVE public. But the CVE has published from MITRE are pretty much useless:

- They lack the vendor / product / version, aka CPE (so far, because CPE are not the end of the world so far), and this is what you are looking for: *you monitor the activity on the CPE you use,* not mere CVE, this is the most important thing to get.
- They lack the CVSS, that you need in order to prioritize your work.
- They do have CWE, but this his mere "dinner for schmucks" / "stamps collectors" metadata, of not much use to you unless you have a  big / middle collection of data that could hint you like "hey, it seems our developers are missing something, because they make the same type of mistakes over and over again".
- They do have references (a set of URL related to the issue, like vendor advisories or link to mailing list such as oss-sec, possibly with a PoC or exploit), but not tagged IIRC.
- Plus a couple over "dinner for schmucks" / "stamps collectors" metadata like the CAPEC = reverse side of the CWE.

None of this is MITRE's job, which is a "private, not for profit company" handling some paperwork for the US federal administration. *Everything begin with the first reference, which allow the CVE to be transferred to NIST*, where the actual works begin, with:
- one or more CPE, this can and will change over time,
- a CVSS, this can and will change over time,
-  tagged references (PoC, Exploit, vendor advisories, mitigations, workarounds, temporary fixe, official fix...) , this can and will change over time,

*What you monitor are the CPE you use, not CVE. Your CPE catalog (I hope you have one, don't you?) is your very precious apple of your eyes. And the CPE info is in the NVD, not MITRE,* so there is not much efficient work you can do before the CVE switch from MITRE to the NVD.

Unless you have the resources to analyze, prioritize and fix issues within a couple of hours, just relax, forget about MITRE and just wait until the issue pop up on the NVD (and the other ecosystems I mention, such as the CISA catalog of know exploited vulnerabilities, InTheWild.io, and OSV which is a completely separate system without CVE nor CPE nor anything of this king).
