### ISSUE TITLE
Can't install on Ubuntu 22.04 LTS due to jsmin dependency on 2to3

### ISSUE THREAD

**Issue by chelgrian** [opencve/opencve#198]
## Expected Behavior
pip install opencve works

## Actual Behavior
The install fails with when installing jsmin with

'error in js_min setup use_2to3 is invalid'

This appears to be because ubuntu 22.04 LTS uses setuptools 59.6.0 however 2to3 was removed from setuptools in version 58 

## Steps to Reproduce the Problem
On an ubuntu 22.04 LTS machine or any machine with setuptools > 58

  - pip install opencve

observe failure while installing jsmin

## Specifications

  - OpenCVE version: 1.3.0 (latest from PyPi)
  - Python version: 3.10.4
  - Platform: Linux/Ubuntu 22.04

**Comment by ncrocfer** [comment]
OpenCVE doesn't support this Python version (see https://github.com/opencve/opencve/blob/master/setup.py#L38) because of old Flask depencencies.

I started to migration all the application in Django (https://github.com/opencve/opencve/tree/dev/ncrocfer/django_migration) but I missed time to finish it. This will be the solution, I will not upgrade Flask codebase.
