### ISSUE TITLE
[issue] Vendors/products are empty

### ISSUE THREAD

**Issue by sdmzn** [opencve/opencve#215]
Hello,

I  started a new docker instance for on-prem installation, all went well except that the Vendor/Products are empty..
![opencve](https://user-images.githubusercontent.com/40860932/185741939-d85b8fcb-a64d-4620-a0f1-b1e265be4f36.jpg)

**Comment by ncrocfer** [comment]
What's your log? Did you check existing issues before creating this one?

- https://github.com/opencve/opencve/issues/67
- https://github.com/opencve/opencve/issues/161
- https://github.com/opencve/opencve/issues/130

**Comment by rfuehrer** [comment]
@sdmzn Tip from my side (since I also ran into this situation): Please increase the RAM available for Docker Desktop (or your Docker instance). At least for me, I think this was set to 3-4GB and should be set to at least 5GB once for the installation, according to the instructions.

![image](https://user-images.githubusercontent.com/25303664/185847656-ec39d5cd-cc76-4305-8112-a789df7cb3a9.png)

Unfortunately you have to start the installation process from the beginning: Delete containers and volumes (Postgres) and perform installation steps again.

**Comment by sdmzn** [comment]
Hello @rfuehrer thank you for the help! it was fixed after setting the memory to 5gb,
my bad, i didnt understand fully the instruction.
