### ISSUE TITLE
No Email-Notification on CVE creation

### ISSUE THREAD

**Issue by bergerb-com** [opencve/opencve#264]
Currently I can only select "As soon as a change is detected" for Email-Notifications. It would be great to receive a notification, when the CVE is created and not only when it is changed.

For example: [CVE-2023-21761](https://www.opencve.io/cve/CVE-2023-21761) was created on 10/01/2023, but I only got the Mail-Notification on 18/01/2023, which was when the CVE was changed.

I don't really understand why that is not implemented, since time is pretty critical, especially for new CVEs?
Maybe I just configured the notification page wrong, but I got every box ticked, or is there something else to be aware of?

**Comment by ncrocfer** [comment]
This is not a bug or a bad implementation, you have to understand how the MITRE/NVD releases the CVE :smiley:

Most of the time when a CVE is published, no **CPE** is associated. So in the case of [CVE-2023-21761](https://www.opencve.io/cve/CVE-2023-21761), when the NVD published it on 10/01/2023 OpenCVE didn't know you were interested by it because even if you subscribed to Microsoft... this CVE **was not** yet linked to Microsoft !

The 18/01/2023 the CPE list was added, including Microsoft vendor. This time OpenCVE was able to retrieve the list of subscribers, including you, so it notified you.

It simple to see the history at the bottom of the page:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/1552526/220172846-0ffec029-5ce2-4423-9e02-7ecb1703c161.png">
