### ISSUE TITLE
Email notification does not work while password reset emails work

### ISSUE THREAD

**Issue by ValentinGep** [opencve/opencve#275]
Hello Teams.

## Expected Behavior

  - Email notification working
  - Email reset password working 

## Actual Behavior

  - Email notification not working
  - Email reset password working 

## Report

Currently, I have the ability to receive "reset password" emails but the notification emails do not work.

To test, I installed the docker version and added the same configuration as the "manual installation" (identical Smtp configuration).

With the docker version the notification emails reach my mailbox.

I don't understand what could be wrong. 
- Is it a bug? 
- a bad configuration?
- How to debug?

## Specifications

  - OpenCVE version: latest
  - Python version: 3.9.2
  - Platform:  Debian 11

###  **OpenCVE.cfg "Manual installation"**

<img width="423" alt="OpenCVE_CONF" src="https://user-images.githubusercontent.com/128030349/225565815-75ec835f-10ec-43d5-aa3a-8c90ba4a1fd1.png">

 ###**OpenCVE.cfg "Docker installation"**

<img width="421" alt="Docker_OpenCVE_CONF" src="https://user-images.githubusercontent.com/128030349/225567980-d1499c4f-08c4-4923-8c15-fd2be3d80e63.png">

**Comment by ncrocfer** [comment]
If you receive an email when you reset your password it means your SMTP configuration is ok.

So the problem comes from your subscriptions (remember OpenCVE only send you alerts when a change matches your subscriptions and your notifications settings).

If you select `CVSS > 8`, or only when a new CPE is detected, or whatever, you reduce the number of notifications (which is a good practive, otherwise we receive to many alerts).

**Comment by ValentinGep** [comment]
Problem solved in our case.
We created a new VM and sending emails worked
