### ISSUE TITLE
Unable to install OpenCVE 

### ISSUE THREAD

**Issue by BlaCkMatiK** [opencve/opencve#283]
## Expected Behavior
Installation

## Actual Behavior
Error raised : *"ERROR: Service 'webserver' failed to build: The command '/bin/sh -c python3 -m pip install /opencve/' returned a non-zero code: 1"*

## Steps to Reproduce the Problem

  - Follow the Docker install of OpenCVE
  - **OR**
  - Follow the pip install of OpenCVE

## Specifications

  - OpenCVE version: v1.4.0
  - Python version: v3.8
  - Platform: Ubuntu / Debian

## Screenshots (optional) 
![image](https://github.com/opencve/opencve/assets/49946898/e9d24fba-2cfb-4366-a62d-116edb123c13)
(*Screenshot from the docker install on Ubuntu*)

**Comment by matiferrigno** [comment]
Hi @BlaCkMatiK ,

I mentioned in this issue https://github.com/opencve/opencve-docker/issues/44 the answer to de docker installation method.

And in the case of `pip install opencve` is because there is no a new release 1.4.1 with the fix that a week ago  @ncrocfer did on requirements.txt. 

I wonder if some mantainer could think the posibility of generate a new release 1.4.1 with this fix ? Thanks !

**Comment by ncrocfer** [comment]
The 1.4.1 version of OpenCVE fixing this issue has been released this week: https://github.com/opencve/opencve/releases/tag/v1.4.1
