### ISSUE TITLE
Problem with web includes when executed in remote server

### ISSUE THREAD

**Issue by megavexus** [opencve/opencve#29]
When i run the server in another server, with the command `$ opencve webserver -b 0.0.0.0:8000`, i found that the webserver use the implicit inclusion of static files, and all the urls are like this: <script src="http://0.0.0.0:8000/static/js/jquery.min.js" type="text/javascript"></script>

(below, a screenshot of the problem)
![imagen](https://user-images.githubusercontent.com/5712587/104005114-ed245600-51a4-11eb-9240-fa173d385d83.png)

**Comment by megavexus** [comment]
I resolve it setting empty in the opencve.cfg the server_name.

**Comment by stedeluxe** [comment]
you may also find you need to invoke the webserver with:

**opencve webserver -b N.N.N.N:8000**

**Comment by ncrocfer** [comment]
@megavexus I don't exactly understand if you still have a problem ? The correct way to use OpenCVE is :

1. launch webserver with your wanted port,
2. configure `server_name` in the config file.

Is-it ok ?

**Comment by DraugurHundur** [comment]
I am not sure this is the same issue but I had a hard time running opencve behind a reverse proxy. server_name had to match the name of the reverse proxy (use_reverse_proxy did not help). Otherwise all the pages would return 404.
To make opencve work on opencve.mydomain.com, I had to:
* on the proxy, override in /etc/hosts opencve.mydomain.com to point to my local instance (e.g. 10.0.1.2 opencve.mydomain.com)
* add an entry in /etc/hosts on the opencve server to do the same.
* on the reverse proxy using apache, use (actual configuration a little different as my proxy is the TLS/SSL endpoint):
```
  <VirtualHost *:80>
    ProxyPreserveHost On

    ProxyPass / http://10.0.1.2:80/
    ProxyPassReverse / http://10.0.1.2:8080/
</VirtualHost>
```
* for opencve use -b 0.0.0.0:80 or -b 10.0.1.2:80 to make sure gunicorn listen on the right port/IP.

**Comment by ncrocfer** [comment]
Thanks for this information @DraugurHundur !

@megavexus do you use a reverse proxy ?

**Comment by ncrocfer** [comment]
Closed due to inactivity of requester.

**Comment by astonbitecode** [comment]
I had the same issue and, even if having the `server_name` empty helped with the GUI, the reports and alerting were not working. I managed to have everything working without reverse proxy like following:

Suppose your server DNS is _myopencve.myhost.com_.

In the `opencve.cfg`, put the server DNS:

```cfg
server_name = myopencve.myhost.com:8000
```

Then, in the docker-compose.yml, webserver section, change the `command` entry and add an `extra_host`:

```yml
command: webserver -b myopencve.myhost.com:8000
extra_hosts:
    - "myopencve.myhost.com:0.0.0.0"
```

This way, the webserver binds to 0.0.0.0, it can be accessible from outside and alerting/reports work fine!
