### ISSUE TITLE
No mail received when CVSS score is empty

### ISSUE THREAD

**Issue by ValentinGep** [opencve/opencve#292]
Hi 

I am encountering a problem,
being subscribed to the "PAN-OS" Product, I should have received an email for the following CVE:

CVE-2023-38046

As you can see from my screenshot, this vulnerability does not present CVSS, CWE and CPE.

![image](https://github.com/opencve/opencve/assets/128030349/961c0f6e-e3fb-41ab-82aa-ee8460067ecd)

I understand that OpenCVE just enumerates NVD database data.
![image](https://github.com/opencve/opencve/assets/128030349/561b8844-c101-4698-80c7-dd8999be07a7)

What I understand is that in the current configuration of OpenCVE, it is impossible to receive a notification by mail when the value is not between [0 and 9].
Currently the return value is "empty".

![image](https://github.com/opencve/opencve/assets/128030349/8b11f343-29c8-4e67-8a2f-4aa29c68d1bd)

Do you have a solution ?

**Comment by ncrocfer** [comment]
Nothing related to the CVSS score of this CVSS, you didn't receive notifications because no **CPEs** has been linked to this CVE:

<img width="1414" alt="image" src="https://github.com/opencve/opencve/assets/1552526/be833e2a-716f-4c00-ae74-b954016ebb46">

So even if you subscribed to the "PAN-OS" Product, OpenCVE can not know this CVE is linked to your wanted subscription, so it didn't alert you. When the NVD will add the CPEs, you will receive alerts.
