### ISSUE TITLE
opencve.io emails are blacklisted

### ISSUE THREAD

**Issue by tuzmadar** [opencve/opencve#295]
## Expected Behavior
Emails from no-reply@opencvie.io should should be received.

## Actual Behavior
Emails are not received by certain providers as opencve.io is apparently blacklisted according to https://mxtoolbox.com/

## Steps to Reproduce the Problem

  - Go to mxtoolbox.com
  - Do an MX lookup on opencve.io
  - Click the blacklist check link

## Specifications

  - OpenCVE version: hosted
  - Python version: n/a
  - Platform: n/a

**Comment by ncrocfer** [comment]
Hi @tuzmadar,

Indeed we already seen that in the past. That's because the IP of our ISP falls into a poor reputation range, so we inherit this blacklist.

By checking our logs we didn't notice any problems in the queues (only issues like "The email account that you tried to reach is over quota").

Because it's not a problem related to the tool itself I will close this issue. But if you think you're impacted by that please contact me directly on [Twitter](https://twitter.com/ncrocfer) we'll check that in PM.
