### ISSUE TITLE
This is not a good approach that if there is one row, so there are all rows!

### ISSUE THREAD

**Issue by mozhdehk** [opencve/opencve#299]
Hi Nicolas
As I had downloading DB (import data) my Internet connection was disconnected.
After that I tried to download the rest of data but I got this message: “Import already done.”.

I searched in your code and found these in __init__.py file:
      def import_data(confirm):
          """
          Perform initial imports (cve, cwe, cpe).
          """
         if Cve.query.**_first():_**
              info("Import already done.")
            return
      ...
I think this is not a good approach that if there is one row, so there are all rows!
What must we do to import all data again?
Sincerely

**Comment by ncrocfer** [comment]
What a title :fire: :laughing:

Did you check the rest of the code behind this snippet? If I added this condition it's because the code behind it is not compatible with an **upsert** mode.

This command has to be launched one time, and only one time at the beginning of your OpenCVE usage. It's not a *normal* usecase to relaunch it several time. And losing your internet connection is not a normal situation ^^

So just drop and recreate your database, pay attention yo your connection and OpenCVE will work for you  :smiley:

Some help for you: https://github.com/opencve/opencve/issues/296

**Comment by mozhdehk** [comment]
> What a title 🔥 😆
> 
> Did you check the rest of the code behind this snippet? If I added this condition it's because the code behind it is not compatible with an **upsert** mode.
> 
> This command has to be launched one time, and only one time at the beginning of your OpenCVE usage. It's not a _normal_ usecase to relaunch it several time. And losing your internet connection is not a normal situation ^^
> 
> So just drop and recreate your database, pay attention to your connection and OpenCVE will work for you 😃
> 
> Some help for you: #296

Hi there,
Thank you very much for your answer and your attention.
I'll try to run and use OpenCVE.
It could not receive updates yet. 
Sincerely
