### ISSUE TITLE
Celery Worker error : "Lock not acquired, skipping"

### ISSUE THREAD

**Issue by Camel0101** [opencve/opencve#313]
## Actual Behavior
I installed the OpenCVE docker following the official documentation but when I start docker compose, the cve updates are not done and it says "Lock not acquired, skipping"
![image](https://github.com/opencve/opencve/assets/110290987/0ea43dfd-f27e-4e63-9786-b87beb8362fd)

## Steps to Reproduce the Problem

  - docker compose up

## Specifications

  - OpenCVE version: 1.4.1
  - Python version: python3.8
  - Platform: Ubuntu 20.04

**Comment by ncrocfer** [comment]
This is a protection to avoid multiple task running in parallel: https://github.com/opencve/opencve/blob/4e422eaabe9f1db4cf8c85802d0cb4ebf07baada/opencve/tasks/__init__.py#L44-L50

A TTL of 12 hours is released, so normally it's ok now. Check if you don't have multiple tasks running in the same time (`docker ps`), maybe it's the problem here.
