### ISSUE TITLE
OpenCve Website does not send E-Mail Notifications

### ISSUE THREAD

**Issue by exequze** [opencve/opencve#354]
## Expected Behavior

When a Cve is changed or added an E-Mail is sent out.

## Actual Behavior

It does not send any E-Mail Notification

## Steps to Reproduce the Problem

  - Go to the Website and Create an Account
  - Add your desired Products
  - Wait for the Cve to be added/changed
  - In Settings->Report filters: check every box; CVSSv3 Score greater than or equal to:1
  - Enable email notifications: yes; as soon as a change is detected
  - See that you did not get an E-Mail

## Specifications

  - OpenCVE version:
  - Python version:
  - Platform: www.opencve.io

## Screenshots (optional)

**Comment by ncrocfer** [comment]
We don't have any issues on OpenCVE.io. I just checked and I can confirm you new mails have been sent today to users.

We often have this kind of question and I'm pretty sure it's the same explanations: vendors and products are parsed from CPEs configuration. Most of the time when a CVE is published it doesn't contain any CPE. That's why users see in the description their wanted keyword "myproduct" for instance, but as it doesn't contain any CPE OpenCVE can not notify you. So you have to wait until CPE are added.

If you need more information you will have to give me your username or your email (you can DM me on Twitter or LinkedIn). Without this information I will not be able to help you and I will close this issue as their is no bug on the tool itself neither on OpenCVE.io
