### ISSUE TITLE
Mail notification not working

### ISSUE THREAD

**Issue by chronosexodata** [opencve/opencve#358]
Hello,

I subscribed to some vendors and activated mail notification whenever a new cve is created. However, I did not receive any mail. 

See below capture.
<img width="865" alt="image" src="https://github.com/opencve/opencve/assets/164994029/ab31cdec-4f1d-421f-bf77-cc8d10066b53">

<img width="896" alt="image" src="https://github.com/opencve/opencve/assets/164994029/f2157b9d-4174-4c6a-ad65-e2aa9ea3d6f3">

Could you describe if I am doing something wrong and help me plz?

Regards

**Comment by ncrocfer** [comment]
It's working, but your configuration is too restrictive. You also have to select **one of your subscriptions appears for the first time in an existing CVE**.

The reason is it's very rare to receive a CVE with already populated CPEs. Most of the time the MITRE creates an empy CVE and then some vendors and products are attached to it.

**Comment by chronosexodata** [comment]
Thank you @ncrocfer , I will try and see if this resolves the issue.
