### ISSUE TITLE
Docker Installation leading to nonfunctional opencve

### ISSUE THREAD

**Issue by achiskon** [opencve/opencve#361]
## Expected Behavior

Work

## Actual Behavior

Does not work, OpenCVE interface intermittently loading, gunicorn webserver and postgres restarting constantly (can't tell which one restarts first)

## Steps to Reproduce the Problem

Just use the documentation to install via docker in a Debian-based VM in 2024.

## Specifications

  - OpenCVE version: where does it say the version
  - Python version: it's Docker
  - Platform: Debian 12.5 and Ubuntu 22.04

## Screenshots (optional)

![Screenshot 2024-04-03 at 2 12 49 PM](https://github.com/opencve/opencve/assets/25139213/132c611f-33b5-449d-94d6-ce36c304f18f)

I really cannot find a way to use OpenCVE as of March/April 2024... The manual installation is a nightmare absolutely does not work with Python versions above 3.8, with several plugins failing or being deprecated... So that's why I turned to Docker, which installs successfully but does not work in the end, as the containers restart one after another miserably.. I tested in two different VMs..

Has anyone tested this software in not-3-years-old OS?

**Comment by ncrocfer** [comment]
```
- ... the manual installation is a nightmare ...
- ... as the containers restart one after another miserably ...
- ... has anyone tested this software in not-3-years-old OS ...
```

This is really not the best issue we have received since the release of OpenCVE :smile:

Because I see in your profile that it's your first issue in Github, I will give you some tips concerning your requests for help in opensource communities:

- be **respectful** in your comments
- stay **calm**, even if things don't go your way
- give more **context** (you're saying that you're trying to *use OpenCVE as of March/April 2024* but it's the first time you ask help here, we can't guess your previouses issues)
- remember people are not working for you, you use a **free tool** without thanking anyone, the least you can do is ask your question politely :wink:

So let's say this kind of issue is *unwelcome* in the Github community.

To answer your question **Has anyone tested this software in not-3-years-old OS?**, yes we do it using the Docker installation without any problems.

**Comment by achiskon** [comment]
You are correct about my ill-tempered attitude. It was inappropriate..
It seems to be a problem with newer kernels and my hypervisor. Thank you..

to make something productive out of my issue, I would suggest that the documentation states that one should attempt to use the manual installation (non docker) guide on current OS (Ubuntu 22) and its current repositories (including current Python) as it is incompatible.

**Comment by achiskon** [comment]
UPDATE:

There really seems to be an issue... No matter how and where I test, the opencve site (via docker) will randomly freeze for 20-30 seconds. I can confirm the webserver is restarted (and restarts postgres as well, due to restart policy possibly - or the other way around) via running "docker logs -f webserver"

**Comment by ncrocfer** [comment]
I close this issue dur to its inactivity. It seems the community doesn't have this issue, as well as us in our own production instance.

Moreover the v2 is a full rewrite of the codebase, so this issue will disappear in it.
