### ISSUE TITLE
No vendor/product in CVE report

### ISSUE THREAD

**Issue by mitch2k** [opencve/opencve#383]
Sometimes CVE's don't have a product or vendor linked. Because of this we don't get alerted and we are missing some CVE's
Example: https://www.opencve.io/cve/CVE-2024-22273

PS: thanks for this awesome project.

## Expected Behavior
Show vendor/product link in the CVE.

## Actual Behavior
No vendor/product link in the CVE.

## Steps to Reproduce the Problem
Check https://www.opencve.io/cve/CVE-2024-22273

## Specifications
Public opencve site

**Comment by markus-lassfolk** [comment]
I think the issue is that some CVE's sometimes lack that information which is what CISA is trying to address here; 
[https://github.com/cisagov/vulnrichment?tab=readme-ov-file#cpe-strings](https://github.com/cisagov/vulnrichment?tab=readme-ov-file#cpe-strings) 
So that will probably be solved with opencve v2 when it's pulling info from more than NVD, right @ncrocfer ?

**Comment by ncrocfer** [comment]
Exactly, we're working to add Vulnrichment in OpenCVE v2.

BTW Vulnrichment has been officially added yesterday as the first one ADP: https://www.cve.org/Media/News/item/blog/2024/06/04/CISA-Added-as-CVE-Authorized-Data-Publisher

In fact the parsing has already been developed and is functional:
<img width="873" alt="image" src="https://github.com/opencve/opencve/assets/1552526/dd23de39-f6d8-431b-8fc1-9b1ac5972a5f">

I just replied today on another issue concerning the OpenCVE v2 ETAs: https://github.com/opencve/opencve/issues/385#issuecomment-2149496473
