### ISSUE TITLE
OpenCVE is not accessed with the existing account

### ISSUE THREAD

**Issue by NLoi7** [opencve/opencve#414]
## Expected Behavior

A few days ago, I had successfully accessed the OpenCVE, but currently, I have no longer to connect on this platform with the same account 

## Actual Behavior

A few days ago, I successfully accessed the OpenCVE, but currently, I can no longer connect to this platform with the same account 

## Steps to Reproduce the Problem

  - Firstly, I tried to connect to OpenCVE, but the issue showed that the username or password was incorrect.
  - Then, I tried to reset my password via email, but the issue still occurred.
  - Finally, I tried to create a new account, but unfortunately, the issue showed that the account already existed.
   

## Specifications

  - OpenCVE version: latest version
  - Python version: I dont know 
  - Platform: I dont know

**Comment by ncrocfer** [comment]
Hello,

Some users have already reported a similar question, and in fact they were using their email instead of their username. Can you verify that this is not the case please?

Anyway discussions related to the SaaS version of OpenCVE (OpenCVE.io) are not handled through this GitHub repository, which is dedicated to the open-source software only, so I will close this issue.

For this kind of questions please feel free to reach out to us directly at [support@opencve.io](mailto:support@opencve.io).
