### ISSUE TITLE
Email notifications fail silently without task failure

### ISSUE THREAD

**Issue by rajtarn** [opencve/opencve#447]
## Expected Behavior
When an email notification fails to be sent, it would be helpful if the task were marked as failed in airflow.
This helps with troubleshooting possible misconfigurations or other problems.

## Actual Behavior
When an email notification fails, the error is only logged, not raised again.
As a result the task is marked as successfully completed, but it is not.

## Steps to Reproduce the Problem

  - Create a malformed email configuration.
  - Run the DAG.
  - No email will be received, but the task will still be marked as successful.

## Specifications

  - OpenCVE version:  v2 (commit c49ab59680eeb0a45a4f4289094972ea74dfd20d)
  - Python version: Any
  - Platform: Any

**Comment by ncrocfer** [comment]
Hello @rajtarn ,

I just replied to your PR, from my answer:

> Unfortunately I think raising an error here is a not good idea as it will break the whole DAG run. For instance let's imagine you have 100 notifications to send, 1 email and 99 webhooks. If SMTP is not configured properly, all webhook notifications will not be sent either.

I think the best here is to do a kind of "precheck" before running the scheduler, in order to verify if your SMTP settings are good. For instance if you use the same SMTP configuration as the web component, you can check if everything is working by asking a password reset. If it's ok you can reuse the same settings in the scheduler.

Also the errors logs are prefixed with`SMTPException` or `Exception` messages, you can easily grep them 😉
