### ISSUE TITLE
Unable to start webserver

### ISSUE THREAD

**Issue by Xumeiquer** [opencve/opencve#65]
## Expected Behavior
The command `opencve webserver` launches the webserver

## Actual Behavior
The command `opencve webserver` throws an error

## Steps to Reproduce the Problem

```python
C:\projects\opencve> opencve webserver
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\projects\opencve\sbox\Scripts\gunicorn.exe\__main__.py", line 4, in <module>
  File "c:\projects\opencve\sbox\lib\site-packages\gunicorn\app\wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "c:\projects\opencve\sbox\lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "c:\projects\opencve\sbox\lib\site-packages\gunicorn\util.py", line 9, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

## Specifications

  - OpenCVE version: 1.0.2
  - Python version: 3.9.1
  - Platform: Windows

## Potential solutions

Instead of using `gunicorn` an option for Windows platforms could be [waitress](https://docs.pylonsproject.org/projects/waitress/en/stable/index.html). Adding `waitress==1.4.4` in the requirements and then checking for the platform in the webserver command will do the job. The change will be something like:

```python
def webserver(args):
    """Run the webserver."""
    if sys.platform == 'win32':
        args = ["waitress-serve"] + list(args)
    else:
        args = ["gunicorn"] + list(args)
    args.append("opencve.app:app")
    os.execvp(args[0], args)
```

**Comment by ncrocfer** [comment]
I'm not sure to dedicate lot's of times on the windows support. I'm not fan to add `if` code for a specific platform.

The webserver is a component and `waitress` can be used instead of `Gunicorn`, it will work here, but I'm pretty sure we'll have other problems on other components for the Windows support. And I'm not sure all the requirements used by OpenCVE are Windows compliant.

One day the tests will not passed on Windows for a new feature, and we'll search a workaround during many hours. Finally it will be a dirty `if sys.platform == "win32"` and I don't want that.

Plus the fact that I don't have Windows on my side and it will not be practical at all to try it during the development, I prefer to indicate in the documentation to use [Windows Subsystem for Linux ](https://docs.microsoft.com/en-us/windows/wsl/).
