### ISSUE TITLE
OpenCVE require stmp_password instead of smtp_password

### ISSUE THREAD

**Issue by Kharec** [opencve/opencve#76]
## Expected Behavior

In opencve.cfg, the option to set SMTP password should be smtp_password.

## Actual Behavior

Actually, it's stmp_password.

```
[mail]
; Choices are 'smtp' or 'sendmail'
email_adapter = smtp

; The 'From' field of the sent emails
email_from = no-reply@opencve.smtp.intranet

; Configuration to set up SMTP mails.
smtp_server = tata.smtp.intranet
smtp_port = 465
smtp_username = toto
stmp_password = tata
```

If you start opencve with smtp_password option instead of stmp_password option, it basically crashes saying "stmp_password option not found".

## Steps to Reproduce the Problem

  - install opencve with pip
  - cat opencve.cfg

## Specifications

  - OpenCVE version: 1.0.2
  - Python version: 3.6.9
  - Platform: Debian 10

Thanks.

**Comment by ncrocfer** [comment]
Ouch, well spotted ! Thanks for this issue ;)

**Comment by Kharec** [comment]
I work on a patch, I'll submit it during the week ;)

**Comment by ncrocfer** [comment]
Great! 

Just one note before submitting your patch : keep the compatibility with the old name please (the one with the typo : `stmp_password`). 

It's important because some people already uses it, and we should not break their instance if they upgrade OpenCVE.

Later we'll deprecate this variable to only support the good one. 

Thanks again for your help ;)

**Comment by Kharec** [comment]
> Just one note before submitting your patch : keep the compatibility with the old name please (the one with the typo : `stmp_password`).
> 
> It's important because some people already uses it, and we should not break their instance if they upgrade OpenCVE.
> 

Yes of course !

You're welcome.
