### ISSUE TITLE
Celery is not downloading new CVE

### ISSUE THREAD

**Issue by Xumeiquer** [opencve/opencve#83]
## Expected Behavior
CVE being downloaded

## Actual Behavior
The CVE database got stuck 

## Steps to Reproduce the Problem
 There are no special steps, I run the OpenCVE as indicated in the README.md. I can see the Celery logs like `Scheduler: Sending due task cve-updates-15-mn (CVE_UPDATES)` and `INFO/SpawnPoolWorker-122] child process 5544 calling self.run()`, but the CVE number is not growing.

I also used [flower](https://github.com/mher/flower) to investigate why the CVEs are not getting downloaded. I could see the broker online with only 7 tasks processed, but they are either not failed or succeeded.

## Specifications
  - OpenCVE version: 1.0.2
  - Python version: 3.9
  - Platform: Windows Server 2016

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/2176256/112609881-60407e80-8e1c-11eb-8143-110f1185b32a.png)

**Comment by ncrocfer** [comment]
OpenCVE don't support Windows, or at least we never tested it on this platform.

OpenCVE works well on Linux (tested on debian-like OS) and we never had this problem. Also I can see several issues from you talking about problems on Windows, so the only thing we can do is to suggest you to use our supported requirements.

In this case we'll be able to help you in case of problems, not here.

I close this issue because Windows is not supported and we certainly won't support it in the future.
